# Communication Codes
INITIALIZE = "INITIALIZE"
VENV = "VENV"
APPROVE = "APPROVE"
DATA = "DATA"
ERROR = "ERROR"
CLOSE = "CLOSE"
TEST_CONNECTION = "TEST_CONNECTION"



# Error Codes
INVALID_FUNCTION_NAM = "Error 1"
MODULE_DOES_NOT_EXIST = "Error 2"
INCORRECT_PARAMETER_COUNT = "Error 3"
INCORRECT_PARAMETER_TYPE = "Error 4"
INVALID_FUNCTION_NAM = "Error 5"
INVALID_FUNCTION_NAM = "Error 6"